SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mydb`.`pets` 
CHANGE COLUMN `idpets` `idpets` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `pet` `pet` VARCHAR(45) NOT NULL ;

ALTER TABLE `mydb`.`cities` 
CHANGE COLUMN `city` `city` VARCHAR(45) NOT NULL ;

ALTER TABLE `mydb`.`languages` 
CHANGE COLUMN `idlanguages` `idlanguages` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `language` `language` VARCHAR(45) NOT NULL ;

ALTER TABLE `mydb`.`genders` 
CHANGE COLUMN `idgenders` `idgenders` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `gender` `gender` VARCHAR(45) NOT NULL ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
