<!DOCTYPE html 
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Spicylicious - Premium HTML template by D.Koev</title>
<link rel="stylesheet" href="/stylesheet/stylesheet.css" 
type="text/css" media="screen" />

<link href='http://fonts.googleapis.com/css?family=Lobster' 
	rel='stylesheet' type='text/css'/>
	
	
<link rel="stylesheet" type="text/css" 
	href="/stylesheet/jquery-ui-1.8.9.custom.css" />
	
	
<!-- jQuery and Custom scripts -->
<script src="/js/jquery-1.5.2.min.js" type="text/javascript"></script>


<script src="/js/jquery.cycle.lite.1.0.min.js" 
type="text/javascript"></script>

<script src="/js/custom_scripts.js" type="text/javascript"></script>
<script src="/js/jquery.roundabout.min.js" type="text/javascript"></script>

<script type="text/javascript" src="/js/jquery-ui-1.8.9.custom.min.js">
</script>


<script type="text/javascript" src="/js/tabs.js"></script>
<!-- Tipsy -->
<script src="/js/tipsy/jquery.tipsy.js" type="text/javascript"></script>
<link href="/js/tipsy/css.tipsy.css" rel="stylesheet" type="text/css" />
<script src="/js/jquery.tweet.js" type="text/javascript"></script>
<link href="/js/jquery.tweet.css" rel="stylesheet" type="text/css" />
</head>

<body>
<!-- MAIN WRAPPER -->
<div id="container"> 
  
  <?php
  include ("/../views/layouts/partials/sides.php");
  ?>
  
  <?php
  include ("/../views/layouts/partials/header.php");
  ?>
  
  <?php
  echo $content;
  //include ("/../views/layouts/partials/content.php");
  ?>
  
  <?php
  include ("/../views/layouts/partials/prefooter.php");
  ?>
  
  <?php
  include ("/../views/layouts/partials/footer.php");
  ?>
    
</div>
<!-- END OF MAIN WRAPPER --> 
<script type="text/javascript" 
src="http://twitter.com/javascripts/blogger.js"></script> 
<script type="text/javascript" 
src="http://twitter.com/statuses/user_timeline/d_koev.json?callback=twitterCallback2&amp;count=3"></script> 
<script type="text/javascript"><!--
$(document).ready(function() {
$('#twitter_update_list').cycle({
		fx: 'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
		next:   '#tweet_next', 
    	prev:   '#tweet_prev'
		}); 
		});
//--></script> 
<script type="text/javascript">
   $(document).ready(function() {
		var interval;
		$('ul#myRoundabout')
		.roundabout({
		  	'btnNext': '.next_round',
			'btnPrev': '.previous_round' 
		  }
		  )
		.hover(
		function() {

		clearInterval(interval);
		},
		function() {

		interval = startAutoPlay();
		});

		interval = startAutoPlay();
		});
		function startAutoPlay() {
		return setInterval(function() {
		$('ul#myRoundabout').roundabout_animateToPreviousChild();
		}, 3000);
	} 
</script>
</body>
</html>
